from datetime import date

from sqlalchemy.orm import Session

from app.models import Patient


PATIENT_SEED_DATA = [
    {
        "first_name": "Amelia",
        "last_name": "Nguyen",
        "date_of_birth": date(1984, 3, 12),
        "phone": "415-555-0198",
        "email": "amelia.nguyen@example.com",
        "address": "2189 Pine Street, San Francisco, CA 94115",
        "blood_type": "O+",
        "allergies": "Penicillin",
        "conditions": "Hypertension",
        "status": "active",
        "last_visit": date(2026, 4, 18),
    },
    {
        "first_name": "Marcus",
        "last_name": "Johnson",
        "date_of_birth": date(1976, 9, 5),
        "phone": "312-555-0144",
        "email": "marcus.johnson@example.com",
        "address": "742 West Monroe Street, Chicago, IL 60607",
        "blood_type": "A-",
        "allergies": "None",
        "conditions": "Type 2 diabetes",
        "status": "active",
        "last_visit": date(2026, 5, 2),
    },
    {
        "first_name": "Sofia",
        "last_name": "Martinez",
        "date_of_birth": date(1991, 1, 27),
        "phone": "602-555-0171",
        "email": "sofia.martinez@example.com",
        "address": "1318 East Camelback Road, Phoenix, AZ 85014",
        "blood_type": "B+",
        "allergies": "Sulfa drugs",
        "conditions": "Asthma",
        "status": "pending",
        "last_visit": date(2026, 3, 29),
    },
    {
        "first_name": "Ethan",
        "last_name": "Patel",
        "date_of_birth": date(1968, 11, 14),
        "phone": "617-555-0162",
        "email": "ethan.patel@example.com",
        "address": "96 Beacon Street, Boston, MA 02108",
        "blood_type": "AB+",
        "allergies": "Latex",
        "conditions": "Coronary artery disease",
        "status": "inactive",
        "last_visit": date(2025, 12, 9),
    },
    {
        "first_name": "Olivia",
        "last_name": "Chen",
        "date_of_birth": date(2000, 7, 22),
        "phone": "206-555-0180",
        "email": "olivia.chen@example.com",
        "address": "508 Queen Anne Avenue N, Seattle, WA 98109",
        "blood_type": "O-",
        "allergies": "Peanuts",
        "conditions": "Migraine",
        "status": "active",
        "last_visit": date(2026, 5, 21),
    },
    {
        "first_name": "Noah",
        "last_name": "Williams",
        "date_of_birth": date(1959, 5, 8),
        "phone": "404-555-0125",
        "email": "noah.williams@example.com",
        "address": "184 Peachtree Street NE, Atlanta, GA 30303",
        "blood_type": "A+",
        "allergies": "Iodine contrast",
        "conditions": "Chronic kidney disease",
        "status": "discharged",
        "last_visit": date(2026, 1, 30),
    },
    {
        "first_name": "Mia",
        "last_name": "Garcia",
        "date_of_birth": date(1989, 10, 3),
        "phone": "210-555-0157",
        "email": "mia.garcia@example.com",
        "address": "602 East Commerce Street, San Antonio, TX 78205",
        "blood_type": "B-",
        "allergies": "Shellfish",
        "conditions": "Hypothyroidism",
        "status": "active",
        "last_visit": date(2026, 4, 7),
    },
    {
        "first_name": "Liam",
        "last_name": "Brown",
        "date_of_birth": date(1972, 2, 19),
        "phone": "303-555-0189",
        "email": "liam.brown@example.com",
        "address": "1550 Wynkoop Street, Denver, CO 80202",
        "blood_type": "O+",
        "allergies": "Aspirin",
        "conditions": "Atrial fibrillation",
        "status": "pending",
        "last_visit": date(2026, 2, 16),
    },
    {
        "first_name": "Isabella",
        "last_name": "Davis",
        "date_of_birth": date(1997, 6, 11),
        "phone": "305-555-0116",
        "email": "isabella.davis@example.com",
        "address": "2390 Biscayne Boulevard, Miami, FL 33137",
        "blood_type": "AB-",
        "allergies": "None",
        "conditions": "Anxiety",
        "status": "active",
        "last_visit": date(2026, 5, 13),
    },
    {
        "first_name": "James",
        "last_name": "Wilson",
        "date_of_birth": date(1948, 12, 1),
        "phone": "215-555-0139",
        "email": "james.wilson@example.com",
        "address": "820 Walnut Street, Philadelphia, PA 19107",
        "blood_type": "A+",
        "allergies": "Codeine",
        "conditions": "COPD",
        "status": "inactive",
        "last_visit": date(2025, 10, 24),
    },
    {
        "first_name": "Ava",
        "last_name": "Thompson",
        "date_of_birth": date(1982, 8, 30),
        "phone": "503-555-0168",
        "email": "ava.thompson@example.com",
        "address": "721 NW 9th Avenue, Portland, OR 97209",
        "blood_type": "B+",
        "allergies": "Tree nuts",
        "conditions": "Rheumatoid arthritis",
        "status": "active",
        "last_visit": date(2026, 4, 25),
    },
    {
        "first_name": "Benjamin",
        "last_name": "Lee",
        "date_of_birth": date(1994, 4, 17),
        "phone": "213-555-0104",
        "email": "benjamin.lee@example.com",
        "address": "900 Wilshire Boulevard, Los Angeles, CA 90017",
        "blood_type": "O-",
        "allergies": "None",
        "conditions": "Eczema",
        "status": "discharged",
        "last_visit": date(2026, 2, 3),
    },
    {
        "first_name": "Charlotte",
        "last_name": "Anderson",
        "date_of_birth": date(1963, 7, 6),
        "phone": "704-555-0151",
        "email": "charlotte.anderson@example.com",
        "address": "340 North Tryon Street, Charlotte, NC 28202",
        "blood_type": "A-",
        "allergies": "Morphine",
        "conditions": "Osteoporosis",
        "status": "active",
        "last_visit": date(2026, 3, 18),
    },
    {
        "first_name": "Lucas",
        "last_name": "Taylor",
        "date_of_birth": date(1987, 11, 28),
        "phone": "615-555-0192",
        "email": "lucas.taylor@example.com",
        "address": "510 Broadway, Nashville, TN 37203",
        "blood_type": "AB+",
        "allergies": "Bee stings",
        "conditions": "GERD",
        "status": "pending",
        "last_visit": date(2026, 1, 12),
    },
    {
        "first_name": "Harper",
        "last_name": "Moore",
        "date_of_birth": date(2003, 2, 9),
        "phone": "801-555-0174",
        "email": "harper.moore@example.com",
        "address": "44 South Main Street, Salt Lake City, UT 84101",
        "blood_type": "B-",
        "allergies": "Dairy",
        "conditions": "Iron deficiency anemia",
        "status": "active",
        "last_visit": date(2026, 5, 8),
    },
    {
        "first_name": "Henry",
        "last_name": "Jackson",
        "date_of_birth": date(1955, 9, 23),
        "phone": "313-555-0181",
        "email": "henry.jackson@example.com",
        "address": "1515 Woodward Avenue, Detroit, MI 48226",
        "blood_type": "O+",
        "allergies": "NSAIDs",
        "conditions": "Heart failure",
        "status": "inactive",
        "last_visit": date(2025, 11, 15),
    },
    {
        "first_name": "Evelyn",
        "last_name": "White",
        "date_of_birth": date(1979, 12, 20),
        "phone": "612-555-0122",
        "email": "evelyn.white@example.com",
        "address": "80 South 8th Street, Minneapolis, MN 55402",
        "blood_type": "A+",
        "allergies": "Cephalosporins",
        "conditions": "Depression",
        "status": "discharged",
        "last_visit": date(2026, 3, 4),
    },
    {
        "first_name": "Alexander",
        "last_name": "Harris",
        "date_of_birth": date(1999, 5, 31),
        "phone": "702-555-0134",
        "email": "alexander.harris@example.com",
        "address": "300 South 4th Street, Las Vegas, NV 89101",
        "blood_type": "AB-",
        "allergies": "None",
        "conditions": "Seasonal allergies",
        "status": "active",
        "last_visit": date(2026, 4, 30),
    },
    {
        "first_name": "Abigail",
        "last_name": "Martin",
        "date_of_birth": date(1970, 1, 16),
        "phone": "919-555-0165",
        "email": "abigail.martin@example.com",
        "address": "421 Fayetteville Street, Raleigh, NC 27601",
        "blood_type": "B+",
        "allergies": "Eggs",
        "conditions": "High cholesterol",
        "status": "pending",
        "last_visit": date(2026, 2, 26),
    },
    {
        "first_name": "Daniel",
        "last_name": "Robinson",
        "date_of_birth": date(1985, 6, 2),
        "phone": "816-555-0108",
        "email": "daniel.robinson@example.com",
        "address": "1100 Main Street, Kansas City, MO 64105",
        "blood_type": "O-",
        "allergies": "Penicillin",
        "conditions": "Sleep apnea",
        "status": "active",
        "last_visit": date(2026, 5, 27),
    },
]


def seed_patients(db: Session) -> None:
    existing_patient = db.query(Patient).first()
    if existing_patient is not None:
        return

    db.add_all(Patient(**patient_data) for patient_data in PATIENT_SEED_DATA)
    db.commit()

